/* jni_bridge.c — aggregator: one shared library, all translation units. */
#include "doc_warp.c"
#include "doc_scan.c"
#include "portrait_blur.c"
#include "zoom_smooth.c"
#include "denoise.c"
#include "sharpen.c"
#include "histogram.c"
#include "color_grade.c"
#include "tone_curve.c"
